### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Thomas-Vos** [artehe/Netimobiledevice#1]
Hi @artehe, an upcoming project of mine needs a way to communicate with iOS devices over USB, and your library seems to exactly that! I am considering using your library, however, the license for Netimobiledevice does not allow dynamic linking from a closed-source application. Is there any chance you can change the license to a more permissive one? A license which allows closed-source applications to link dynamically to your open-source library would be great.

**Comment by artehe** [comment]
Hey, sure I don't see a problem with changing the license.

Is there one that you would recommend I change it to?

**Comment by Thomas-Vos** [comment]
That's very nice, thanks.

You could use LGPL, which is very similar to GPL, but it does allow dynamic linking from a closed source app.

From what I can see it still requires library users to publish source code of Netimobiledevice in case it was modified (which is no problem for me).

It also must provide users the ability to be able to replace the Netimobiledevice dll in a published app. This is difficult for a (signed) Microsoft Store app (like my app). I think it would be fine but I am not sure as modifying the app and get it running would be very complicated for a user. So I am not sure publishing to the Microsoft Store would be allowed with LGPL.

Alternatively, a license such as Apache 2.0 or MIT would be easier to work with as they don't have such restrictions. I know I can use those on the Microsoft Store. But that depends on what you want.

Thanks for considering changing the license, it would be great if I can use your library.

**Comment by artehe** [comment]
Cool, I've changed the license to be MIT, should work for you just fine.

**Comment by Thomas-Vos** [comment]
Thanks a lot, that's great! I will definitely be using your library. By the way there is also a License heading in the README.md file.
