### ISSUE TITLE
Can't create and/or connect to Usbmux socket

### ISSUE THREAD

**Issue by Mrf2233** [artehe/Netimobiledevice#20]
This library throws exceptions when I use both iPhone 7 and iphone13.
Error Code:
` List<UsbmuxdDevice> devices = Usbmux.GetDeviceList();`

**Comment by PElanchezhiyan** [comment]
@794742233 , Have you made the device to be trust? Also, we need to unlock the mobile for the first time pair? I have used both the mobiles and used iPhone 15 as well and it works fine.

**Comment by artehe** [comment]
@794742233 You haven't actually posted what the exception is which happened just the function which I guess threw the error? Also it would help if you provided a little more information such as what OS you are using.

@Elanchezhiyan-P To interact with usbmux and retrieve a list of connected devices it shouldn't need to be trusted.

**Comment by 794742233** [comment]
> @794742233 You haven't actually posted what the exception is which happened just the function which I guess threw the error? Also it would help if you provided a little more information such as what OS you are using.
> 
> @Elanchezhiyan-P To interact with usbmux and retrieve a list of connected devices it shouldn't need to be trusted.

I first connected the iPhone to the PC via USB. After using the software to show that the phone mirror was successful, I downloaded the project and tried to run the demo program, but there was an error.
`        public UsbmuxdSocket()
        {
            try {
                if (OperatingSystem.IsWindows()) {
                    EndPoint windowsSocketAddress = new IPEndPoint(IPAddress.Parse(USBMUXD_SOCKET_IP), USBMUXD_SOCKET_PORT);
                    socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.IP);
                    socket.Connect(windowsSocketAddress);
                }
                else {
                    UnixDomainSocketEndPoint unixSocketAddress = new UnixDomainSocketEndPoint(USBMUXD_SOCKET_FILE);
                    socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.IP);
                    socket.Connect(unixSocketAddress);
                }
            }
            catch (SocketException ex) {
                throw new UsbmuxConnectionException("Can't create and/or connect to Usbmux socket", ex);//<-------
            }
        }`

**Comment by Elanchezhiyan-P** [comment]
@794742233 , Can you post the video link for reference?

**Comment by artehe** [comment]
@794742233 It sounds like you're using Windows, and the main reason I can think of for that exception to occur is the Drivers/Service which it uses isn't running.

The service if it exists and is running looks like this:
![image](https://github.com/artehe/Netimobiledevice/assets/112902041/e684520d-b27f-4d99-acfe-1e1cb61d0c19)

If you don't have it there's a few ways you can get it, but the easiest is probably just to download iTunes (not the one from Windows Store) and install that.

**Comment by 794742233** [comment]
> iTunes

I'm unlikely to download or use iTunes, I'm trying some of the payware approaches, using libusb to recognize and install drivers to ios devices.
