### ISSUE TITLE
Retrieve the browser history.

### ISSUE THREAD

**Issue by PragadeeshRaj005** [artehe/Netimobiledevice#37]
If it's possible to retrieve the iPhone Safari browser's local history database from connected device?

**Comment by artehe** [comment]
If memory serves the only way to get that out is to do a backup of the device and then read it, however I could be wrong.

**Comment by PElanchezhiyan** [comment]
@artehe  how to redirect this path and take the backup. 
path: /Users/(user)/Library/Safari/History.db 
can you help to take backup from  above path?

**Comment by PragadeeshRaj005** [comment]
@artehe  how to redirect this path and take the backup.
path: /Users/(user)/Library/Safari/History.db
can you help to take backup from above path?

**Comment by PragadeeshRaj005** [comment]
@artehe  how to redirect this path and take the backup.
path: /Users/(user)/Library/Safari/History.db
can you help to take backup from above path?

**Comment by artehe** [comment]
You should be able to find whatever the path is in the Manifest.db, all the file paths etc are listed in there.
