### ISSUE TITLE
The documentation inthe readme no longer seems to match the implmenation

### ISSUE THREAD

**Issue by MarkFassett** [artehe/Netimobiledevice#39]
We're updating to the 1.0 release, but the documentation no longer seems to match. LockdownClient no longer has a CreateLockdownClient method, but instead has a `Create` method that takes a ServiceConnection as well as the id (and potentially a bunch of other things). 

The demo seems to do things much differently, too...

**Comment by ShivankChopra** [comment]
Hi. For now you can refer to examples(tests?) in this repo for latest version reference.

**Comment by MarkFassett** [comment]
> You can find latest version example here
> 
> ```
> NetimobiledeviceDemo/Program.cs
> ```

This is an issue, not a help request. I mentioned the demo, and was already aware of it.
