### ISSUE TITLE
Invalid message sent to usbmuxd when creating a new connection

### ISSUE THREAD

**Issue by dmdmdm-nz** [artehe/Netimobiledevice#46]
**Describe the bug**
When trying to enumerate devices on Linux `Netimobiledevice` reports that it's unable to connect to `usbmuxd`.

I've tried the same code on Windows and macOS and it works. We're running a recent version `libimobiledevice/usbmuxd` so potentially it's more strict than `usbmuxd` is on Windows/macOS.

After doing a bit of digging it appears that the `UsbmuxConnection::Create` method sends an invalid `ReadBUID` message to `usbmuxd` and so it terminates the connection.

**Additional context**

The `UsbmuxConnection::Create` method sends the `ReadBUID` message to `usbmuxd`:

```csharp
PropertyNode plistMessage = new StringNode("ReadBUID");
conn.Send(plistMessage);
PlistResponse response = conn.ReceivePlist(tag);
```

Instead, this code should be:

```csharp
DictionaryNode msg = new DictionaryNode() {
    { "MessageType", new StringNode("ReadBUID") }
};
conn.Send(plistMessage);
PlistResponse response = conn.ReceivePlist(tag);
```

**Comment by artehe** [comment]
That's a good spot thank you. I must admit I haven't done any testing on Linux.

Will make the change on Monday and test it out. However if you don't want to wait till then feel free to make a pr with this 😁

**Comment by dmdmdm-nz** [comment]
Thanks @artehe ... I've added a PR with the change.
