### ISSUE TITLE
safari browser history

### ISSUE THREAD

**Issue by PElanchezhiyan** [artehe/Netimobiledevice#58]
hi @artehe  Our current library does not retrieve the history database and call history database. Is it possible to include the call history and Safari browser history databases in our backup functionality

**Comment by artehe** [comment]
If these database aren't in a normal iOS backup then it's possible that they are only included in an encrypted backup have you checked if they are in one of those?

**Comment by PElanchezhiyan** [comment]
@artehe  we have the option to encrypt the backup using our library?

**Comment by artehe** [comment]
Yes you can check if encryption is already enabled by querying lockdown doing something like this:

```csharp
DictionaryNode? backupDomain = Lockdown.GetValue("com.apple.mobile.backup", null)?.AsDictionaryNode();
backupDomain?.TryGetValue("WillEncrypt", out PropertyNode? isEncryptedNode);
boolean isEncrypted = isEncryptedNode?.AsBooleanNode().Value ?? false;
```

Then if it isn't set you can enable it by setting a backup password using the Mobilebackup2Service.SetBackupPassword function. You can find about this here: https://github.com/artehe/Netimobiledevice/blob/aa671c3fb0915e60e98dd32e57afe94cc9ae9cdb/Netimobiledevice/Backup/Mobilebackup2Service.cs#L237
