### ISSUE TITLE
Bulk retrieval

### ISSUE THREAD

**Issue by PElanchezhiyan** [artehe/Netimobiledevice#60]
Hi, @artehe .  Our library backup method currently sends a request and processes responses in a loop. Is there a way to obtain the complete backup from the phone in a single operation, allowing for bulk retrieval of the entire backup transfer at once, instead of handling responses individually?

**Comment by artehe** [comment]
If you're using the latest master branch then do you mean doing the following:

```csharp
CancellationTokenSource tokenSource = new CancellationTokenSource();
using (UsbmuxLockdownClient lockdown = MobileDevice.CreateUsingUsbmux("60653a518d33eb53b3ca2322de3f44e162a42069")) {
    using (Mobilebackup2Service mb2 = new Mobilebackup2Service(lockdown)) {
        await mb2.Backup(true, "backups", tokenSource.Token);
    }
}
```

That'd run the entire backup and wait for it to complete before continuing
