### ISSUE TITLE
Read root directory and populate the images.

### ISSUE THREAD

**Issue by Elanchezhiyan-AIT** [artehe/Netimobiledevice#9]
How do i read the root directory and populate the images present in the location of the iOS device? I have tried with the IOS_Pilot package to Read the directory, but it was made of dot net framework. I was not able to add/use those functionalities. Let me know if there is any way to call this function or have Read Directory function in AFCService?

**Comment by artehe** [comment]
I don't believe that any read directory function is currently implemented, mainly just file reading things to do an iOS backup. 

From what is already setup in the AfcService class it should be relatively simple to add, if you'd like this feel free to do it yourself and make a PR.

**Comment by artehe** [comment]
I've no idea if you've done anything with this but I had some time today and thought I'd have a go at adding directory reading.

It's in the linked branch if you want to have a look and see what you think of it.

**Comment by Elanchezhiyan-AIT** [comment]
@artehe , I have completed it locally and used it for my reference. I haven't added it to it. Let me know if i can create PR for this process.

**Comment by artehe** [comment]
Of course you can.

Please feel free to and I'll take a look at it.

**Comment by PElanchezhiyan** [comment]
#12 , I have raised PR. Please review and let me know if there are any changes required.
